expected results
a100WithoutDependencies
	^ 'CGOPackageUnit {
	#package : #A,
	#description : ''A test package version.'',
	#version : ''1.0.0'',
	#timestamp : DateAndTime [ ''2015-02-26T12:17:20.505912+01:00'' ],
	#dependencies : [ ],
	#src : CGOMonticelloHostedPackageVersion {
		#repositoryUrl : ''http://smalltalkhub.com/mc/Foo/Bar/main'',
		#packageName : #no-file-specified,
		#versionString : ''JohnDoe.0''
	}
}'