expected results
a100With2EmptyDependency
	^ 'CGOPackageUnit {
	#package : #A,
	#description : ''A test package version.'',
	#version : ''1.0.0'',
	#timestamp : DateAndTime [ ''2015-02-26T12:17:20.505912+01:00'' ],
	#dependencies : [
		#B : [ ],
		#C : [ ]
	],
	#src : CGOMonticelloHostedPackageVersion {
		#repositoryUrl : ''http://smalltalkhub.com/mc/Foo/Bar/main/'',
		#versionString : ''JohnDoe.0''
	}
}'