expected results
seasideCore310StonString
	^ 'CGOPackageUnit {
	#package : #Seaside-Core,
	#description : ''No description'',
	#version : ''3.1.0'',
	#timestamp : DateAndTime [ ''2015-02-26T12:17:20.505912+01:00'' ],
	#dependencies : [
		#Grease-Core : [
			''=1.1.5''
		],
		#Seaside-Core-Platform : [
			''=3.1.0''
		]
	],
	#repositories : [
		''http://smalltalkhub.com/mc/Seaside/Seaside31/main/''
	],
	#file : ''Seaside-Core-pmm.808''
}'