as yet unclassified
dependencies
	^ { #'Core' -> #('=3.1') .
		#'Seaside-Tests-Core' -> #('=3.1') .
		#'Seaside-Tests-Canvas' -> #('=3.1') .
		#'Seaside-Tests-Session' -> #('=3.1') .
		#'Seaside-Tests-Component' -> #('=3.1') .
		#'Seaside-Tests-RenderLoop' -> #('=3.1') .
		#'Seaside-Tests-Environment' -> #('=3.1') .
		#'Seaside-Tests-Flow' -> #('=3.1') .
		#'Seaside-Tests-UTF8' -> #('=3.1') .
		#'Seaside-Tests-InternetExplorer' -> #('=3.1') .
		#'Seaside-Tests-Email' -> #('=3.1') .
		#'Seaside-Tests-Examples' -> #('=3.1') .
		#'RSS Tests' -> #('=3.1') .
		#'Welcome Tests' -> #('=3.1') . }