input
input
	"Seaside31 resolution"
	^  'CGOLoadInstructions {
	#groups : OrderedCollection [
		CGOPackageLoadGroup {
			#name : #Grease-Core,
			#packageVersionRefs : [
				CGOPackageVersionReference {
					#packageName : #Grease-Core,
					#versionNumber : ''1.1.5''
				},
				CGOPackageVersionReference {
					#packageName : #Grease-Pharo30-Core,
					#versionNumber : ''1.1.5''
				}
			]
		},
		CGOPackageLoadGroup {
			#name : #Seaside-Core,
			#packageVersionRefs : [
				CGOPackageVersionReference {
					#packageName : #Seaside-Core,
					#versionNumber : ''3.1.0''
				},
				CGOPackageVersionReference {
					#packageName : #Seaside-Pharo20-Core,
					#versionNumber : ''3.1.0''
				}
			]
		},
		CGOPackageLoadGroup {
			#name : #Seaside-Canvas,
			#packageVersionRefs : [
				CGOPackageVersionReference {
					#packageName : #Seaside-Canvas,
					#versionNumber : ''3.1.0''
				},
				CGOPackageVersionReference {
					#packageName : #Seaside-Pharo-Canvas,
					#versionNumber : ''3.1.0''
				}
			]
		},
		CGOPackageLoadGroup {
			#name : #Seaside-Session,
			#packageVersionRefs : [
				CGOPackageVersionReference {
					#packageName : #Seaside-Session,
					#versionNumber : ''3.1.0''
				}
			]
		},
		CGOPackageLoadGroup {
			#name : #Seaside-Component,
			#packageVersionRefs : [
				CGOPackageVersionReference {
					#packageName : #Seaside-Component,
					#versionNumber : ''3.1.0''
				}
			]
		},
		CGOPackageLoadGroup {
			#name : #Seaside-RenderLoop,
			#packageVersionRefs : [
				CGOPackageVersionReference {
					#packageName : #Seaside-RenderLoop,
					#versionNumber : ''3.1.0''
				}
			]
		},
		CGOPackageLoadGroup {
			#name : #Javascript-Core,
			#packageVersionRefs : [
				CGOPackageVersionReference {
					#packageName : #Javascript-Core,
					#versionNumber : ''3.1.0''
				},
				CGOPackageVersionReference {
					#packageName : #Javascript-Pharo20-Core,
					#versionNumber : ''3.1.0''
				}
			]
		},
		CGOPackageLoadGroup {
			#name : #Seaside-Pharo-Continuation,
			#packageVersionRefs : [
				CGOPackageVersionReference {
					#packageName : #Seaside-Pharo-Continuation,
					#versionNumber : ''3.1.0''
				}
			]
		},
		CGOPackageLoadGroup {
			#name : #Seaside-Tools-Core,
			#packageVersionRefs : [
				CGOPackageVersionReference {
					#packageName : #Seaside-Tools-Core,
					#versionNumber : ''3.1.0''
				},
				CGOPackageVersionReference {
					#packageName : #Seaside-Pharo-Tools-Spec,
					#versionNumber : ''3.1.0''
				}
			]
		},
		CGOPackageLoadGroup {
			#name : #Seaside-Widgets,
			#packageVersionRefs : [
				CGOPackageVersionReference {
					#packageName : #Seaside-Widgets,
					#versionNumber : ''3.1.0''
				}
			]
		},
		CGOPackageLoadGroup {
			#name : #Zinc-Resource-Meta-Core,
			#packageVersionRefs : [
				CGOPackageVersionReference {
					#packageName : #Zinc-Resource-Meta-Core,
					#versionNumber : ''2.4.8''
				}
			]
		},
		CGOPackageLoadGroup {
			#name : #Zinc-Character-Encoding,
			#packageVersionRefs : [
				CGOPackageVersionReference {
					#packageName : #Zinc-Character-Encoding,
					#versionNumber : ''2.4.8''
				}
			]
		},
		CGOPackageLoadGroup {
			#name : #JQuery-Core,
			#packageVersionRefs : [
				CGOPackageVersionReference {
					#packageName : #JQuery-Core,
					#versionNumber : ''3.1.0''
				}
			]
		},
		CGOPackageLoadGroup {
			#name : #Seaside-Flow,
			#packageVersionRefs : [
				CGOPackageVersionReference {
					#packageName : #Seaside-Flow,
					#versionNumber : ''3.1.0''
				},
				CGOPackageVersionReference {
					#packageName : #Seaside-Pharo-Flow,
					#versionNumber : ''3.1.0''
				}
			]
		},
		CGOPackageLoadGroup {
			#name : #Seaside-Tools-Web,
			#packageVersionRefs : [
				CGOPackageVersionReference {
					#packageName : #Seaside-Tools-Web,
					#versionNumber : ''3.1.0''
				},
				CGOPackageVersionReference {
					#packageName : #Seaside-Pharo20-Tools-Web,
					#versionNumber : ''3.1.0''
				}
			]
		},
		CGOPackageLoadGroup {
			#name : #Zinc-HTTP,
			#packageVersionRefs : [
				CGOPackageVersionReference {
					#packageName : #Zinc-HTTP,
					#versionNumber : ''2.4.8''
				}
			]
		},
		CGOPackageLoadGroup {
			#name : #JQuery-UI,
			#packageVersionRefs : [
				CGOPackageVersionReference {
					#packageName : #JQuery-UI,
					#versionNumber : ''3.1.0''
				}
			]
		},
		CGOPackageLoadGroup {
			#name : #Seaside-Development,
			#packageVersionRefs : [
				CGOPackageVersionReference {
					#packageName : #Seaside-Development,
					#versionNumber : ''3.1.0''
				},
				CGOPackageVersionReference {
					#packageName : #Seaside-Pharo-Development,
					#versionNumber : ''3.1.0''
				}
			]
		},
		CGOPackageLoadGroup {
			#name : #Seaside-Examples,
			#packageVersionRefs : [
				CGOPackageVersionReference {
					#packageName : #Seaside-Examples,
					#versionNumber : ''3.1.0''
				}
			]
		},
		CGOPackageLoadGroup {
			#name : #Seaside-Environment,
			#packageVersionRefs : [
				CGOPackageVersionReference {
					#packageName : #Seaside-Environment,
					#versionNumber : ''3.1.0''
				},
				CGOPackageVersionReference {
					#packageName : #Seaside-Pharo-Environment,
					#versionNumber : ''3.1.0''
				}
			]
		},
		CGOPackageLoadGroup {
			#name : #Zinc-Seaside,
			#packageVersionRefs : [
				CGOPackageVersionReference {
					#packageName : #Zinc-Seaside,
					#versionNumber : ''3.1.0''
				}
			]
		},
		CGOPackageLoadGroup {
			#name : #Seaside-Welcome,
			#packageVersionRefs : [
				CGOPackageVersionReference {
					#packageName : #Seaside-Welcome,
					#versionNumber : ''3.1.0''
				},
				CGOPackageVersionReference {
					#packageName : #Seaside-Pharo-Welcome,
					#versionNumber : ''3.1.0''
				}
			]
		},
		CGOPackageLoadGroup {
			#name : #Seaside-Group-Default,
			#packageVersionRefs : [
				CGOPackageVersionReference {
					#packageName : #Seaside-Group-Default,
					#versionNumber : ''3.1.0''
				}
			]
		},
		CGOPackageLoadGroup {
			#name : #Seaside31,
			#packageVersionRefs : [
				CGOPackageVersionReference {
					#packageName : #Seaside31,
					#versionNumber : ''3.1.0''
				}
			]
		}
	]
}'