SystemOrganization addCategory: #'CargoPackageManager-TestRessources'!
SystemOrganization addCategory: #'CargoPackageManager-TestRessources-Resources'!
SystemOrganization addCategory: #'CargoPackageManager-TestRessources-SeasideDesc-Adaptors'!
SystemOrganization addCategory: #'CargoPackageManager-TestRessources-SeasideDesc-Common'!
SystemOrganization addCategory: #'CargoPackageManager-TestRessources-SeasideDesc-JsJquery'!
SystemOrganization addCategory: #'CargoPackageManager-TestRessources-SeasideDesc-Pharo'!
SystemOrganization addCategory: #'CargoPackageManager-TestRessources-SeasideDesc-Welcome'!
