SystemOrganization addCategory: #'CargoPackageManager-Tests'!
SystemOrganization addCategory: #'CargoPackageManager-Tests-Functional'!
SystemOrganization addCategory: #'CargoPackageManager-Tests-Loader'!
SystemOrganization addCategory: #'CargoPackageManager-Tests-Model'!
SystemOrganization addCategory: #'CargoPackageManager-Tests-Model-Serialization'!
SystemOrganization addCategory: #'CargoPackageManager-Tests-PackageRepository'!
SystemOrganization addCategory: #'CargoPackageManager-Tests-SCM'!
SystemOrganization addCategory: #'CargoPackageManager-Tests-Solver'!
