SystemOrganization addCategory: #'CargoPackageManager-Tests'!
SystemOrganization addCategory: #'CargoPackageManager-Tests-LauncherRessource'!
SystemOrganization addCategory: #'CargoPackageManager-Tests-Model'!
SystemOrganization addCategory: #'CargoPackageManager-Tests-Model-Serialization'!
SystemOrganization addCategory: #'CargoPackageManager-Tests-SCM'!
SystemOrganization addCategory: #'CargoPackageManager-Tests-SCM'!
SystemOrganization addCategory: #'CargoPackageManager-Tests-Solver'!
SystemOrganization addCategory: #'CargoPackageManager-Tests-Solver'!
lver'!
SystemOrganization addCategory: #'CargoPackageManager-Tests-Solver'!
