as yet unclassified
diffMetacelloPPM4Seaside31
	"Only loaded by Metacello"
 '		load : Grease-Tests-Core-pmm.94
			load : Grease-Tests-Pharo20-Core-pmm.8
			load : Seaside-Tests-Core-pmm.272
		load : Seaside-Tests-Pharo20-Core-pmm.4
		load : Seaside-Tests-Component-pmm.36
		load : Seaside-Tests-Canvas-pmm.64
		load : Seaside-Tests-Pharo-Canvas-pmm.1
		load : Seaside-Tests-Session-pmm.72
		load : Seaside-Tests-RenderLoop-lr.13
		load : Seaside-Tests-Environment-pmm.30
		load : Seaside-Tests-Functional-pmm.156
		load : Seaside-Tests-Pharo-Functional-pmm.15
		load : Seaside-Tests-Flow-pmm.37
		load : Seaside-Tests-Welcome-lr.6
		load : Seaside-Tests-Pharo-Continuation-pmm.9'