as yet unclassified
metacelloSeaside31Resolution
 Metacello new
  configuration: 'Seaside3';
  version: '3.1.0';
  record. 
	'linear load : 
	linear load : 3.1.0 [ConfigurationOfSeaside3]
		load : ConfigurationOfGrease
	linear load : 3.1.0 [ConfigurationOfSeaside3]
		load : ConfigurationOfGrease
	linear load : 3.1.0 [ConfigurationOfSeaside3]
		explicit load : Grease
			load : ConfigurationOfGrease-pmm.241
		linear load : 1.1.5 [ConfigurationOfGrease]
			load : Grease-Core-JohanBrichau.83
			load : Grease-Pharo30-Core-pmm.11
		linear load : 1.1.5 [ConfigurationOfGrease]
			load : Grease-Tests-Core-pmm.94
			load : Grease-Tests-Pharo20-Core-pmm.8
		load : Seaside-Core-pmm.808
		load : Seaside-Pharo20-Core-pmm.3
		load : Seaside-Component-pmm.101
		load : Seaside-Canvas-pmm.127
		load : Seaside-Pharo-Canvas-pmm.4
		load : Seaside-Session-pmm.168
		load : Seaside-RenderLoop-JohanBrichau.95
		load : Seaside-Tools-Core-pmm.23
		load : Seaside-Pharo-Tools-Spec-pmm.9
		load : Seaside-Flow-pmm.24
		load : Seaside-Examples-pmm.24
		load : Seaside-Widgets-pmm.33
		load : Seaside-Tools-Web-pmm.118
		load : Seaside-Pharo20-Tools-Web-JohanBrichau.3
		load : Seaside-Development-pmm.163
		load : Seaside-Environment-pmm.81
		load : Seaside-Pharo-Environment-lr.6
		load : Seaside-Tests-Core-pmm.272
		load : Seaside-Tests-Pharo20-Core-pmm.4
		load : Seaside-Tests-Component-pmm.36
		load : Seaside-Tests-Canvas-pmm.64
		load : Seaside-Tests-Pharo-Canvas-pmm.1
		load : Seaside-Tests-Session-pmm.72
		load : Seaside-Tests-RenderLoop-lr.13
		load : Seaside-Tests-Environment-pmm.30
		load : Seaside-Tests-Functional-pmm.156
		load : Seaside-Tests-Pharo-Functional-pmm.15
		load : Seaside-Tests-Flow-pmm.37
		load : Zinc-Seaside-SvenVanCaekenberghe.40
		load : Javascript-Core-pmm.95
		load : Javascript-Pharo20-Core-JohanBrichau.4
		load : JQuery-Core-pmm.128
		load : JQuery-UI-pmm.88
		load : Seaside-Welcome-pmm.47
		load : Seaside-Pharo-Welcome-NickAger.2
		load : Seaside-Tests-Welcome-lr.6
		load : Seaside-Pharo-Continuation-lr.5
		load : Seaside-Tests-Pharo-Continuation-pmm.9
		load : Seaside-Pharo-Flow-lr.5
		load : Seaside-Pharo-Development-JohanBrichau.66'