SystemOrganization addCategory: #'CargoPackageManager-FailingTests'!
SystemOrganization addCategory: #'CargoPackageManager-FailingTests-Functional'!
SystemOrganization addCategory: #'CargoPackageManager-FailingTests-Loader'!
SystemOrganization addCategory: #'CargoPackageManager-FailingTests-Model'!
SystemOrganization addCategory: #'CargoPackageManager-FailingTests-Model-Serialization'!
SystemOrganization addCategory: #'CargoPackageManager-FailingTests-PackageRepository'!
SystemOrganization addCategory: #'CargoPackageManager-FailingTests-SCM'!
SystemOrganization addCategory: #'CargoPackageManager-FailingTests-Solver'!
