data - cargo package versions
greasepharo40slime1_1_13
	<cargoPackageVersion>
	^ STON fromString: 
'CGOPackageUnit {
	#package : #Grease-Pharo40-Slime,
	#description : ''Slime uses the Refactoring Browser to find and, in some cases, rewrite common compatibility problems.'',
	#version : ''1.1.13'',
	#timestamp : DateAndTime [ ''2015-05-11T14:56:09.456+00:00'' ],
	#dependencies : [
		#Grease-Core-Platform : [ ]
	],
	#src: CGOMonticelloHostedPackageVersion {
		#repositoryUrl : ''http://smalltalkhub.com/mc/Seaside/Grease11/main/'',
		#packageName : #Grease-Pharo40-Slime,
		#versionString : ''JohanBrichau.3''
	},
	#platformRequirements : [
		''pharo5.x''
	],
	#provisions : [
		''Grease-Slime''
	]
}'