data - cargo package versions
greasecore1_1_13
	<cargoPackageVersion>
	^ STON fromString: 
'CGOPackageUnit {
	#package : #Grease-Core,
	#description : ''Core package of the Grease library.'',
	#version : ''1.1.13'',
	#timestamp : DateAndTime [ ''2015-04-14T14:51:50.116+00:00'' ],
	#dependencies : [ ],
	#src: CGOMonticelloHostedPackageVersion {
		#repositoryUrl : ''http://smalltalkhub.com/mc/Seaside/Grease11/main/'',
		#packageName : #Grease-Core,
		#versionString : ''JohanBrichau.94''
	}
}'