data - cargo package versions
greasepharo30core1_1_13
	<cargoPackageVersion>
	^ STON fromString: 
'CGOPackageUnit {
	#package : #Grease-Pharo30-Core,
	#description : ''Platform-specific package of the Grease-Core package for Pharo.'',
	#version : ''1.1.13'',
	#timestamp : DateAndTime [ ''2015-05-11T14:56:14.307+00:00'' ],
	#dependencies : [
		#Grease-Core : [ ]
	],
	#repositories : [
		''http://smalltalkhub.com/mc/Seaside/Grease11/main/''
	],
	#platformRequirements : [
		''pharo''
	],
	#provisions : [
		''Grease-Core-Platform''
	],
	#file : ''Grease-Pharo30-Core-JohanBrichau.16''
}'