data - cargo package versions
greasepharo40slime1_1_13
	<cargoPackageVersion>
	^ STON fromString: 
'CGOPackageUnit {
	#package : #Grease-Pharo40-Slime,
	#description : ''Slime uses the Refactoring Browser to find and, in some cases, rewrite common compatibility problems.'',
	#version : ''1.1.13'',
	#timestamp : DateAndTime [ ''2015-05-11T14:56:09.456+00:00'' ],
	#dependencies : [
		#Grease-Core-Platform : [ ]
	],
	#repositories : [
		''http://smalltalkhub.com/mc/Seaside/Grease11/main/''
	],
	#platformRequirements : [
		''pharo5.x''
	],
	#provisions : [
		''Grease-Slime''
	],
	#file : ''Grease-Pharo40-Slime-JohanBrichau.3''
}'