# This is a basic workflow to help you get started with Actions

name: Pakbot-core

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        smalltalk: [ Pharo64-11 ]
        smalltalk_config: [ .core.ston ]
        
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    name: Pakbot core, ${{ matrix.smalltalk }} on ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup smalltalkCI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
          
      - name: Load Image and Run Tests
        run: smalltalkci -s ${{ matrix.smalltalk }} ${{ matrix.smalltalk_config }}
        timeout-minutes: 15
