expected results
seasideCore310StonString
	^ 'CGOPackageUnit {
	#description : ''No description'',
	#version : ''3.1.0'',
	#package : #Seaside-Core,
	#timestamp : DateAndTime [ ''2015-02-26T12:17:20.505912+01:00'' ],
	#src : CGOMonticelloHostedPackageVersion {
		#repository : CGOMonticelloRepository {
			#repositoryUrl : ''http://smalltalkhub.com/mc/Seaside/Seaside31/main''
		},
		#packageName : #Seaside-Core,
		#versionString : ''pmm.808''
	},
	#dependencies : [
		#Grease-Core : [
			''=1.1.5''
		],
		#Seaside-Core-Platform : [
			''=3.1.0''
		]
	]
}'